// src/app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Session } from "inspector/promises";
import { SessionProvider } from "next-auth/react";
import { auth } from "./auth";

export const metadata: Metadata = {
  title: "Riddhi Interiors - Dehradun",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth(); // Get server-side session

  return (
    <html lang="en">
      <body className="antialiased text-foreground dark:bg-black dark:text-white transition-colors bg-amber-100">
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  );
}
